### PR TITLE
Use same bundle version as in jclouds/project/java-xmlbuilder.verison

### PR DESCRIPTION
**Pull request by neykov**
https://github.com/jclouds/jclouds/blob/master/project/pom.xml#L235

### CODE REVIEW

**Comment by demobox** [comment]
Thanks, @neykov! Pending the CI build, looks good to me. For reference for anyone who's interested, this is the bundle, I think:

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22org.apache.servicemix.bundles.java-xmlbuilder%22

**Comment by andreaturli** [comment]
@demobox lgtm too

**Comment by andreaturli** [comment]
thanks @neykov

**Comment by andreaturli** [comment]
@neykov why was that deleted?

**Comment by neykov** [comment]
I've just deleted the PR branch in my repo @andreaturli. The changes are already in jclouds' master.

**Comment by andreaturli** [comment]
not sure why, but it is not in `master` can you re-open this PR, please?

**Comment by neykov** [comment]
Reponed in https://github.com/jclouds/jclouds-karaf/pull/91

**Pull request merged**
