### PR TITLE
Minimize Groovy dependency

### PR DESCRIPTION
**Pull request by andrewgaul**
This shrinks jclouds-cli from 28 MB to 26 MB.

### CODE REVIEW

**Comment by andrewgaul** [comment]
I would be very happy to rip out groovy entirely.

**Comment by nacx** [comment]
Build fails with:

```bash
Could not start bundle mvn:org.apache.jclouds.karaf/commands/2.0.0-SNAPSHOT
    in feature(s) jclouds-commands-2.0.0-SNAPSHOT: Unresolved constraint in bundle org.apache.jclouds.karaf.commands [105]:
    Unable to resolve 105.0: missing requirement [105.0] osgi.wiring.package; (osgi.wiring.package=org.codehaus.groovy.jsr223)
```

Looks like it requires the `groovy-jsr223` dependency?
BTW, do you know what groovy is used for?

**Comment by iocanel** [comment]
groovy is used to allow customisation of the command output via groovy expressions.

**Comment by andrewgaul** [comment]
I added the missing dependency on groovy-jsr223 but the integration tests still fail.  I experience the same symptoms on master without these changes.

**Comment by andrewgaul** [comment]
Odd, this fails locally and passes in CloudBees.

**Pull request merged**
