### PR TITLE
JCLOUDS-669: Add support for openstack-swift and rackspace-cloudfiles

### PR DESCRIPTION
**Pull request by andrewgaul**

### CODE REVIEW

**Comment by andrewgaul** [comment]
@zack-shoylev @iocanel please review

**Comment by nacx** [comment]
Add the corresponding tests to [ApisFeaturesInstallationTest](https://github.com/jclouds/jclouds-karaf/blob/master/itests/src/test/java/org/jclouds/karaf/itests/ApisFeaturesInstallationTest.java) and [RackspaceFeaturesInstallationTest](https://github.com/jclouds/jclouds-karaf/blob/master/itests/src/test/java/org/jclouds/karaf/itests/RackspaceFeaturesInstallationTest.java)

**Comment by zack-shoylev** [comment]
Why not just remove the old providers?

**Comment by andrewgaul** [comment]
I amended the commits to add the suggested tests.  We can remove the legacy support in a subsequent pull request.

**Comment by andrewgaul** [comment]
Odd, not sure why the openstack-swift tests succeed but the rackspace-cloudfiles tests fail?

**Comment by andrewgaul** [comment]
Needed cloudidentity dependency.

**Pull request merged**
